<h1>Über Webeve</h1>

<p>
<h2>Was ist Webeve?</h2>
Webeve ist ein <b>Web</b>basierter <b>Eve</b>ntkalender für Vereine im Raum
Oberfranken. Entstanden ist Webeve aus dem internen Web-Terminkalender des
<a href="http://www.goessenreuth.de/" target="_blank">Burschenvereins Gössenreuth</a>.<br/>
Webeve baut darauf, daß jeder Veranstalter selbst am meisten Interesse hat
seine Veranstaltung möglichst weiträumig bekannt zu machen. Daher pflegt jeder
angemeldete Verein seine Veranstaltungstermine in Webeve selbständig.<br/>
Die Liste der Veranstaltungen kann von jedem Verein in die eigene Webpräsenz
eingebunden und an deren Design angepasst werden. Außerdem existiert eine separate
Ansicht für vereinsinterne Termine.</p>

<p>
<h2>Wer nutzt Webeve?</h2>
Neben dem Burschenverein Gössenreuth nutzen seit 2001 der Bezirksverband der
Landjugend Oberfranken und damit nahezu alle Landjugendgruppen in Oberfranken
Webeve.
</p>

<p>
<h2>Wie kann man Webeve nutzen?</h2>
Sofern Du in der Vorstandschaft eines oberfränkischen Vereins bist oder Du
Terminverwalter eines solchen bist, kannst Du einfach per
Email an <a href="mailto:webmaster@webeve.de">webmaster@webeve.de</a> unter Angabe des Vereinsnamens Deine
Zugangsdaten anfordern.</p>

<p>
<h2>Was kostet Webeve?</h2>
Sowohl für Veranstalter als auch für Partygänger ist die Nutzung
kostenlos. Über das eine oder andere Freibier freue ich mich natürlich
trotzdem. ;) 
</p>

<p>
<h2>Technisches:</h2>
Webeve besteht aus einigen Perl-Scripten die ihre Daten in einer
MySQL Datenbank speichern. Den Quellcode werde ich füher oder später, in
der Hoffnung einige aktive Mitentwickler zu finden, veröffentlichen.
</p>
