<h1>Impressum &amp; Disclaimer</h1>

<p>
  Betreiber:<br/>
  Christopher Hofmann<br/>
  Walter-Meckauer-Str. 13/B24<br/>
  90478 Nürnberg<br/>
  <a href="mailto:webmaster@webeve.de">webmaster@webeve.de</a>
</p>

<p>
<h2>Haftung für Inhalte</h2>
Die Inhalte meiner Seiten wurden mit größter Sorgfalt erstellt. Für die
Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann ich jedoch
keine Gewähr übernehmen.  Als Diensteanbieter bin ich gemäß §6 Abs.1 MDStV
und §8 Abs.1 TDG für eigene Inhalte auf diesen Seiten nach den allgemeinen
Gesetzen verantwortlich. Diensteanbieter sind jedoch nicht verpflichtet, die
von ihnen übermittelten oder gespeicherten fremden Informationen zu überwachen
oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit
hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von
Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine
diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer
konkreten Rechtsverletzung möglich. Bei bekannt werden von entsprechenden
Rechtsverletzungen werde ich diese Inhalte umgehend entfernen.
</p>
<p>
<h2>Haftung für Links</h2>
Mein Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte
ich keinen Einfluss habe. Deshalb kannen ich für diese fremden Inhalte auch
keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der
jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten
Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße
überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht
erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist
jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei
bekannt werden von Rechtsverletzungen werde ich derartige Links umgehend
entfernen.
</p>
<p>
<h2>Urheberrecht</h2>
Die Betreiber der Seiten sind bemüht, stets die Urheberrechte anderer zu
beachten bzw. auf selbst erstellte sowie lizenzfreie Werke zurückzugreifen.
Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten
unterliegen dem deutschen Urheberrecht. Beiträge Dritter sind als solche
gekennzeichnet. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art
der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der
schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und
Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch
gestattet.</p>
<p>
<h2>Datenschutz</h2>
Soweit auf meinen Seiten personenbezogene Daten
(beispielsweise Name, Anschrift oder eMail-Adressen) erhoben werden, erfolgt
dies soweit möglich stets auf freiwilliger Basis. Die Nutzung der Angebote und
Dienste ist, soweit möglich, stets ohne Angabe personenbezogener Daten
möglich.  Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten
Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter
Werbung und Informationsmaterialien wird hiermit ausdrücklich
widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche
Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa
durch Spam-Mails, vor.  </p>

<p>Quelle: <a target="_blank" href="http://www.e-recht24.de/muster-disclaimer.htm">Disclaimer</a>
von <a href="http://www.e-recht24.de">Anwalt</a> Sören Siebert</p>
