<h1>Impressum &amp; Kontakt</h1>

<p>
  Betreiber: Christopher Hofmann<br/>
  Kontakt: <a href="mailto:webmaster@webeve.de">webmaster@webeve.de</a>
</p>

<p>
  <h2>Haftungsausschluß</h2>
  Ich habe keinerlei Einfluß auf den Inhalt der verlinkten Seiten.
  Ebenso habe ich keinen Einfluß auf den Inhalt der gelisteten Termine.
  Hierfür tragen alleine die Autoren der jeweiligen Kalendereinträge die Verantwortung.
  Ich bin nicht in der Lage die hier gespeicherten Termine auf Richtigkeit und evtl.
  strafbaren oder beleidigenden Inhalt zu überprüfen. Solltest Du falsche, strafbare
  oder beleidigende Inhalte feststellen, so bitte ich mir diese unter der o.g.
  Emailadresse mitzuteilen. Ich werde ich diese selbstverständlich korrigieren bzw. löschen.
</p>